//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPolApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int employee_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string full_name { get; set; }
        public string position { get; set; }
        public string passport { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> hire_date { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
