//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPolApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public Materials()
        {
            this.MaterialSupplies = new HashSet<MaterialSupplies>();
            this.Production = new HashSet<Production>();
        }
    
        public int material_id { get; set; }
        public string material_name { get; set; }
        public string material_type { get; set; }
        public Nullable<decimal> defect_rate { get; set; }
        public Nullable<decimal> stock_quantity { get; set; }
    
        public virtual ICollection<MaterialSupplies> MaterialSupplies { get; set; }
        public virtual ICollection<Production> Production { get; set; }
    }
}
