//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPolApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.OrderItems = new HashSet<OrderItems>();
            this.Production = new HashSet<Production>();
        }
    
        public int order_id { get; set; }
        public int partner_id { get; set; }
        public int created_by_user { get; set; }
        public System.DateTime order_date { get; set; }
        public string status { get; set; }
        public Nullable<bool> prepayment { get; set; }
    
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual Users Users { get; set; }
        public virtual Partners Partners { get; set; }
        public virtual ICollection<Production> Production { get; set; }
    }
}
