//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPolApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        public Partners()
        {
            this.Orders = new HashSet<Orders>();
            this.Sales = new HashSet<Sales>();
        }
    
        public int partner_id { get; set; }
        public string partner_type { get; set; }
        public string name { get; set; }
        public string director { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string legal_address { get; set; }
        public string inn { get; set; }
        public Nullable<int> rating { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
