//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPolApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        public int production_id { get; set; }
        public int order_id { get; set; }
        public int product_id { get; set; }
        public int master_user_id { get; set; }
        public int material_id { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public decimal quantity_produced { get; set; }
        public string status { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Users Users { get; set; }
        public virtual Products Products { get; set; }
    }
}
