//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPolApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.OrderItems = new HashSet<OrderItems>();
            this.Production = new HashSet<Production>();
            this.Sales = new HashSet<Sales>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_type { get; set; }
        public Nullable<decimal> coefficient { get; set; }
        public string article { get; set; }
    
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual ICollection<Production> Production { get; set; }
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
