//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPolApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        public Suppliers()
        {
            this.MaterialSupplies = new HashSet<MaterialSupplies>();
        }
    
        public int supplier_id { get; set; }
        public string supplier_name { get; set; }
        public string inn { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<MaterialSupplies> MaterialSupplies { get; set; }
    }
}
