//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPolApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActions
    {
        public int action_id { get; set; }
        public int user_id { get; set; }
        public string action_type { get; set; }
        public string action_description { get; set; }
        public Nullable<System.DateTime> action_time { get; set; }
        public string ip_address { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
