//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPolApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Employees = new HashSet<Employees>();
            this.Orders = new HashSet<Orders>();
            this.Production = new HashSet<Production>();
            this.UserActions = new HashSet<UserActions>();
        }
    
        public int user_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string role { get; set; }
        public string email { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
    
        public virtual ICollection<Employees> Employees { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<Production> Production { get; set; }
        public virtual ICollection<UserActions> UserActions { get; set; }
    }
}
